// middleware/validationMiddleware.js
const { validationResult } = require('express-validator');

/**
 * Middleware to handle validation errors generated by express-validator.
 * Checks if validation errors exist on the request object.
 * If errors are found, it sends a 400 Bad Request response with the errors.
 * Otherwise, it calls the next middleware in the stack.
 */
const handleValidationErrors = (req, res, next) => {
  // Finds the validation errors in this request and wraps them in an object with handy functions
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    // If there are validation errors, return a 400 response with the errors array
    return res.status(400).json({ errors: errors.array() });
  }
  // If no validation errors, proceed to the next middleware or route handler
  next();
};

module.exports = handleValidationErrors;
